version: "3"
#################################################################
##
## THIS FILE CONTAINS A TEST 
##
#################################################################
services:
#################################################################
## CTFD; 
## Testing nginx on ctfd
# STATUS : FUNCTIONAL
#################################################################        
    ctfd:
      image: ctfd/ctfd
      #build:
      #  context: ./containers/ctfd
      #  dockerfile: Dockerfile
      hostname: ctfd
      user: root
      restart: unless-stopped
      environment:
        - UPLOAD_FOLDER=${UPLOAD_FOLDER}
      #  - DATABASE_URL=${DATABASE_URL}
      #  - REDIS_URL=${REDIS_URL}
      #  - WORKERS=${WORKERS}
        - LOG_FOLDER=${LOG_FOLDER}
      #  - ACCESS_LOG=${ACCESS_LOG}
      #  - ERROR_LOG=${ERROR_LOG}
      #  - REVERSE_PROXY=${REVERSE_PROXY}
      env_file:
        - ./.env
      volumes:
      #  - ${CERTBOTCONFVOLUMES}
      #  - ${CERTBOTDATAVOLUMES}
      #  - ${CERTBOTLOGVOLUMES}
        - ./data/CTFd/logs:${LOG_FOLDER}
        - ./data/CTFd/uploads:${UPLOAD_FOLDER}
      #depends_on:
      #  - db
      expose:
        - 8000
      ports:
      #  - 80:80
      #  - 443:443
        - 8000:8000
      #networks:
      #  internal:
      #  net:
        #  ipv4_address: ${CTFDIP}