version: "3"
#################################################################
##
## THIS FILE CONTAINS THE ENTRIES FOR THE INFRASTRUCTURE
##
#################################################################
services:
#################################################################
##  NGINX ; proxies to the other containers
#################################################################        
    nginx:
      build:
        context: ./containers/nginx
        dockerfile: Dockerfile
      image: nginx:latest
      hostname: nginx
      #depends_on:
      #  - bwapp
      #  - dvwa
      #  - ctfd
      restart: unless-stopped
      env_file:
        - ./.env
      ports:
        - 80:80
        - 443:443
      networks:
        net:
          ipv4_address: ${NGINXIP}

#################################################################
##  BWAPP   ; will be locked down for semi-private usage
#################################################################
    bwapp:
      image: raesene/bwapp
      hostname: bwapp
      depends_on:
        - nginx
      expose:
        - 80
      ports:
        - ${BWAPPPORT}:80
      networks:
        net:
          ipv4_address: ${BWAPPIP}

#################################################################
##  Damn Vulnerable WEB APP ; will be locked down for semi-private usage
#################################################################
    dvwa:
      image: vulnerables/web-dvwa
      depends_on:
        - nginx
      hostname: dvwa
      expose:
        - 80
      restart: unless-stopped
      ports:
        - ${DVWAPORT}:80
      networks:
        net:
          ipv4_address: ${DVWAIP}
##################################################################
## OWASP JUICESHOP  ; will be locked down for semi-private usage
#################################################################
#docker run --rm -p 3000:3000 bkimminich/juice-shop
    juiceshop:
      image: bkimminich/juice-shop
      hostname: juiceshop
      depends_on:
        - nginx
      expose:
        - 3000
      restart: unless-stopped
      ports:
        - ${JUICESHOPPORT}:3000
      networks:
        net:
          ipv4_address: ${JUICESHOPIP}
       
#################################################################
##  Mutillidae2 ; will be locked down for semi-private usage
#################################################################
#    mutillidae2:
#      image: santosomar/mutillidae_2
#      restart: unless-stopped
#      ports:
#        - ${MUTILLIDAE2PORT}:80
#      networks:
#        net:
#          ipv4_address: ${MUTILLIDAE2IP}
#################################################################
## CTFD; 
## will use the builder script portion for production. 
#################################################################        
    ctfd:
      image: ctfd/ctfd
      #build:
      #  context: ./containers/CTFd
      #  dockerfile: Dockerfile
      hostname: ctfd
      user: root
      restart: always
      environment:
        - UPLOAD_FOLDER=${UPLOAD_FOLDER}
        - DATABASE_URL=${DATABASE_URL}
        - REDIS_URL=${REDIS_URL}
        - WORKERS=${WORKERS}
        - LOG_FOLDER=${LOG_FOLDER}
        - ACCESS_LOG=${ACCESS_LOG}
        - ERROR_LOG=${ERROR_LOG}
        - REVERSE_PROXY=${REVERSE_PROXY}
      volumes:
        - ./data/CTFd/logs:${LOG_FOLDER}
        - ./data/CTFd/uploads:${UPLOAD_FOLDER}
        - ./data/UIUCTF-2021-Public:/opt/challenges:ro
      depends_on:
        - db
        - nginx
      expose:
        - 8000
      restart: unless-stopped
      ports:
        - ${CTFDPORT}:8000
      networks:
        internal:
        net:
          ipv4_address: ${CTFDIP}

#################################################################
#                   REDIS SERVER
#################################################################
    cache:
      image: redis
      depends_on:
        - nginx
      hostname: cache
      #command: redis-server --appendonly yes
      ports:
        #- ${REDISPORT}:6379
        - 6379:6379
      volumes:
        - ./data/redis:/data
      restart: unless-stopped
      networks:
        internal:
#################################################################
#                   MYSQL SERVER
#################################################################
    db:
      image: mariadb:10.4.12
      depends_on:
        - nginx
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      # This command is required to set important mariadb defaults
      command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]
      volumes:
        - ./data/mysql:/var/lib/mysql
      networks:
          internal:

#################################################################
#     NETWORKS SECTION
#################################################################      
networks:
  internal:
    internal: true

  net:
    ipam:
      config:
        - subnet: "172.18.0.0/24"
    #external: true
