version: "3"
#################################################################
##
## THIS FILE CONTAINS THE ENTRIES FOR THE INFRASTRUCTURE
##
#################################################################
services:
#################################################################
##  NGINX ; proxies to the other containers
#################################################################        
    nginx:
      build:
        context: ./containers/nginx
        dockerfile: Dockerfile
      image: nginx:latest
      depends_on:
        - bwapp
        - dvwa
        - ctfd
      restart: unless-stopped
      env_file:
        - ./.env
      ports:
      - 80:80
      - 443:443
      environment: 
        NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
        NGINX_ENVSUBST_TEMPLATE_DIR: "/etc/nginx"
        NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
      volumes:
        #- ./data/certbot/conf:/etc/letsencrypt
        #- ./data/certbot/www:/var/www/certbot
        - "/run/docker.sock:/var/run/docker.sock"
        #  - ./confs/nginx.conf:/etc/nginx/nginx.conf
      hostname: nginx
      networks:
        net:
          ipv4_address: 172.18.0.3

################################################################
## CERTBOT enables ssl for the backend
################################################################
#    certbot:
#      image: certbot/certbot
#      hostname: certbot
#      #volumes:
#        #- ./data/certbot/conf:/etc/letsencrypt
#        #- ./data/certbot/www:/var/www/certbot
#      networks:
#        net:
#          ipv4_address: 172.18.0.4
#################################################################
##  BWAPP   ; will be locked down for semi-private usage
#################################################################
    bwapp:
      image: raesene/bwapp
      expose:
        - 80
      ports:
        - ${BWAPPPORT}:80
      networks:
        net:
          ipv4_address: ${BWAPPIP}
      hostname: bwapp
##################################################################
## WEB GOAT AND WOLF  ; will be locked down for semi-private usage
#################################################################
#    webgoat:
#      image: webgoat/webgoat-7.1
#      #expose:
#      #  - ${WEEBGOATPORT}
#      restart: unless-stopped
#      ports:
#        - ${WEEBGOATPORT}:8080
#      networks:
#        - net
#################################################################
##  Damn Vulnerable WEB APP ; will be locked down for semi-private usage
#################################################################
    dvwa:
      image: vulnerables/web-dvwa
      hostname: dvwa
      expose:
        - 80
      restart: unless-stopped
      ports:
        - ${DVWAPORT}:80
      networks:
        net:
          ipv4_address: ${DVWAIP}
        
#################################################################
##  Mutillidae2 ; will be locked down for semi-private usage
#################################################################
#    mutillidae2:
#      image: santosomar/mutillidae_2
#      restart: unless-stopped
#      ports:
#        - ${MUTILLIDAE2PORT}:80
#      networks:
#        net:
#          ipv4_address: ${MUTILLIDAE2IP}
#################################################################
## CTFD; 
## will use the builder script portion for production. 
#################################################################        
    ctfd:
      image: ctfd/ctfd
      #build:
      #  context: ./containers/CTFd
      #  dockerfile: Dockerfile
      hostname: ctfd
      user: root
      restart: always
      environment:
        - UPLOAD_FOLDER=${UPLOAD_FOLDER}
        - DATABASE_URL=${DATABASE_URL}
        - REDIS_URL=${REDIS_URL}
        - WORKERS=${WORKERS}
        - LOG_FOLDER=${LOG_FOLDER}
        - ACCESS_LOG=${ACCESS_LOG}
        - ERROR_LOG=${ERROR_LOG}
        - REVERSE_PROXY=${REVERSE_PROXY}
      volumes:
        - ./data/CTFd/logs:${LOG_FOLDER}
        - ./data/CTFd/uploads:${UPLOAD_FOLDER}
        - ./data/UIUCTF-2021-Public:/opt/challenges:ro
      depends_on:
        - db
      expose:
        - 8000
      restart: unless-stopped
      ports:
        - ${CTFDPORT}:8000
      networks:
        default:
        internal:
        net:
          external: true
          ipv4_address: ${CTFDIP}

#################################################################
##  target1 available for pwnage
################################################################
#    cnc:
#      image: debian:buster
#      build:
#        context: ./containers/cnc
#        dockerfile: Dockerfile
#      networks:
#        net:
#          ipv4_address: 172.18.0.2
#################################################################
##  Parrotsec/ParOS
#################################################################
#    parrot:
#      image: parrotsec/security
#      volumes:
#        - "/run/docker.sock:/var/run/docker.sock"
#      networks:
#        net:
#          ipv4_address: 172.18.0.2
#      #volumes:
#      #  -  /tmp/msf:/tmp/data:Z
#      #network_mode: host
#################################################################
#     DATABASE SECTION
#################################################################
    cache:
      image: redis
      hostname: cache
      #command: redis-server --appendonly yes
      ports:
        - ${REDISPORT}:6379
      volumes:
        - ./data/redis:/data
      restart: unless-stopped
      networks:
        internal:
        net:
          ipv4_address: ${REDISIP}

    db:
      image: mariadb:10.4.12
      restart: always
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=${MYSQL_DATABASE}
      volumes:
        - ./data/mysql:/var/lib/mysql
      networks:
          internal:
      # This command is required to set important mariadb defaults
      command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci, --wait_timeout=28800, --log-warnings=0]

#################################################################
#     NETWORKS SECTION
#################################################################      
#networks:
#  macvlan:
networks:
  default:
  internal:
    internal: true
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
  hax:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet ${HAXSUBNETRANGE}