services:
#################################################################
##
##  This file contains the entries for the network hacking
##
#################################################################
##  Parrotsec/ParOS
#################################################################
#    parrot:
#      image: parrotsec/security
#      volumes:
#        - "/run/docker.sock:/var/run/docker.sock"
#      networks:
#        net:
#          ipv4_address: 172.18.0.2
#      #volumes:
#      #  -  /tmp/msf:/tmp/data:Z
#      #network_mode: host
#################################################################
##  target1 available for pwnage
################################################################
  cnc:
    image: debian:buster
    build:
      context: ./containers/cnc
      dockerfile: Dockerfile
    networks:
      hax:
        external: true
        ipv4_address: 172.18.0.2
###############################################################################
## miniaturehorsedb
###############################################################################
  minidb:
    image: mysql
    environment:
      MYSQL_DATABASE: ponies
      MYSQL_USER: iheartponies
      MYSQL_PASSWORD: wv38f8hnDb1IThTw6A
      MYSQL_RANDOM_ROOT_PASSWORD: 1
  miniponydb:
    privileged: true
    build: ${MINIPONYDBBUILDDIR}
    environment:
      FLAG: uiuctf{wh0ops_th1s_on3_was_harder_r1ght_9fa2b}
      DB: ponies
      DB_HOST: minidb
      DB_USER: iheartponies
      DB_PASS: wv38f8hnDb1IThTw6A
      SECRET_KEY: uSsV465Looe1P8
    #and here we deviate
    ports:
      - ${MINIPONYDBPORT}:1337
    networks:
      hax:
        external: true
        ipv4_address: ${MINIPONYDBIP}
###############################################################################
## ponydb
###############################################################################
  pwnydb:
    image: mysql
    environment:
      MYSQL_DATABASE: ponies
      MYSQL_USER: iheartponies
      MYSQL_PASSWORD: wv38f8hnDb1IThTw6A
      MYSQL_RANDOM_ROOT_PASSWORD: 1
  ponydb:
    build: ${PONYDBBUILDDIR}
    environment:
      FLAG: uiuctf{My_l33tle_p0ny}
      DB: ponies
      DB_HOST: pwnydb
      DB_USER: iheartponies
      DB_PASS: wv38f8hnDb1IThTw6A
      SECRET_KEY: uSsV465Looe1P8
    ports:
      - ${PONYDBPORT}:1337
    #and here we deviate
    networks:
      hax:
        external: true
        ipv4_address: ${PONYDBIP}

#################################################################
##  BWAPP   ; will be locked down for semi-private usage
# STATUS : FUNCTIONAL
#################################################################
    bwapp:
      image: raesene/bwapp
      hostname: bwapp
      depends_on:
        - nginx
      expose:
        - 80
      ports:
        - ${BWAPPPORT}:80
      networks:
        hax:
          external: true
          ipv4_address: ${BWAPPIP}

#################################################################
##  Damn Vulnerable WEB APP ; will be locked down for semi-private usage
# STATUS : FUNCTIONAL
#################################################################
    dvwa:
      image: vulnerables/web-dvwa
      depends_on:
        - nginx
      hostname: dvwa
      expose:
        - 80
      restart: unless-stopped
      ports:
        - ${DVWAPORT}:80
      networks:
        hax:
          external: true
          ipv4_address: ${DVWAIP}
#################################################################
## OWASP JUICESHOP  ; will be locked down for semi-private usage
# STATUS : FUNCTIONAL
#################################################################
#docker run --rm -p 3000:3000 bkimminich/juice-shop
    juiceshop:
      image: bkimminich/juice-shop
      hostname: juiceshop
      depends_on:
        - nginx
      expose:
        - 3000
      restart: unless-stopped
      ports:
        - ${JUICESHOPPORT}:3000
      networks:
        hax:
          external: true
          ipv4_address: ${JUICESHOPIP}

#################################################################
##  Mutillidae2 ; will be locked down for semi-private usage
# STATUS : FUNCTIONAL
#################################################################
    mutillidae2:
      image: santosomar/mutillidae_2
      restart: unless-stopped
      ports:
        - ${MUTILLIDAE2PORT}:80
      networks:
        hax:
          external: true
          ipv4_address: ${MUTILLIDAE2IP}
################################################################
#     NETWORKS SECTION
#################################################################      
networks:
  hax:
    external: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${HAXSUBNETRANGE}