version: "3"
#################################################################
##
## THIS FILE CONTAINS THE ENTRIES FOR THE INFRASTRUCTURE
##
## container port mapping to avoid confuflict
##   LOGINPORT=8080
#3   BWAPPPORT=8081
##   WEEBGOATPORT=8082
##   DVWAPORT=8083
##   MUTILLIDAE2PORT=8084
##   CTFDPORT=8085
#################################################################
services:
#################################################################
##  NGINX ; proxies to the other containers
# DEPRECATED in favor of TRAEFIK currently
#################################################################        
    nginx:
      build:
        context: ./containers/nginx
        dockerfile: Dockerfile
      image: nginx:latest
      #depends_on:
      #  - bwapp
      #  - dvwa
      #  - ctfd
      restart: unless-stopped
      env_file:
        - ./.env
      ports:
      - 80:80
      - 443:443
      environment: 
        NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
        NGINX_ENVSUBST_TEMPLATE_DIR: "/etc/nginx"
        NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
      volumes:
      #  - "html:/usr/share/nginx/html/challenges/bwapp"
        - "/run/docker.sock:/var/run/docker.sock"
      #  - ./confs/nginx.conf:/etc/nginx/nginx.conf
      #  - ./letsencrypt/:/etc/letsencrypt/
      #network_mode: host
      hostname: nginx
      networks:
        net:
          ipv4_address: 172.18.0.3
######
#     NETWORKS SECTION
#################################################################      
#networks:
#  macvlan:
networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24