version: "3"

#################################################################
services:
#################################################################
##  Parrotsec/ParOS
#################################################################
    parrot:
      image: parrotsec/security
      volumes:
        - "/run/docker.sock:/var/run/docker.sock"
      networks:
        - net
      #volumes:
      #  -  /tmp/msf:/tmp/data:Z
      #network_mode: host
#################################################################
#     NETWORKS SECTION
#################################################################      
#networks:
#  macvlan:
networks:
  net:
    external: true