#[http.middlewares.simpleAuth.basicAuth]
#  users = [
#    "admin:password"
#  ]

#[http.routers.api]
  #rule = "Host(`dashboard.moopboxen.local`)"
  #entrypoints = ["net"]
  #middlewares = ["simpleAuth"]
  #service = "api@internal"
  #[http.routers.api.tls]
    #certResolver = "lets-encrypt"