version: "3"
#################################################################
##
## THIS FILE CONTAINS THE ENTRIES FOR THE INFRASTRUCTURE
##
## container port mapping to avoid confuflict
##   LOGINPORT=8080
#3   BWAPPPORT=8081
##   WEEBGOATPORT=8082
##   DVWAPORT=8083
##   MUTILLIDAE2PORT=8084
##   CTFDPORT=8085
#################################################################
services:
#################################################################
##  NGINX ; proxies to the other containers
# DEPRECATED in favor of TRAEFIK currently
#################################################################        
    nginx:
      build:
        context: ./nginx
        dockerfile: Dockerfile
      image: nginx:latest
      #depends_on:
      #  - bwapp
      #  - webgoat
      #  - dvwa
      #  - ctfd
      #  - mutillidae2
      restart: unless-stopped
      env_file:
        - ./.env
      ports:
        #- 80:80
        # with traefik added I want to proxy to the proxy
        - 81:80
        - 443:443
      environment: 
        NGINX_ENVSUBST_TEMPLATE_SUFFIX: ".template"
        NGINX_ENVSUBST_TEMPLATE_DIR: "/etc/nginx"
        NGINX_ENVSUBST_OUTPUT_DIR: "/etc/nginx"
      volumes:
      #  - "html:/usr/share/nginx/html/challenges/bwapp"
        - "/run/docker.sock:/var/run/docker.sock:ro"
      #  - ./confs/nginx.conf:/etc/nginx/nginx.conf
      #  - ./letsencrypt/:/etc/letsencrypt/
      #network_mode: host
      networks:
        - frontend
        - containers
        - backend 
#################################################################
#     VOLUMES SECTION
#################################################################      
#volumes:
#a  html:

#################################################################
#     NETWORKS SECTION
#################################################################      
networks:
  containers:
    driver: bridge
  frontend:
    driver: bridge
  backend:
    driver: bridge
